trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container:  mcr.microsoft.com/dotnet/core/sdk:3.1

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'